insert into spectacle values ('101', 'Cats');
insert into spectacle values ('102', 'Metallica');
insert into spectacle values ('103', 'Manu Chao');
insert into spectacle values ('104', 'Cirque du Soleil');
insert into representation values ('101', '06-NOV-08');
insert into representation values ('102', '20-DEC-08');
insert into representation values ('104', '14-JAN-09');
insert into representation values ('104', '20-FEB-09');
insert into representation values ('104', '21-FEB-09');
insert into representation values ('104', '22-FEB-09');